name: "W&B Evaluate + Comparison Report"
on:
  repository_dispatch:
    types: "evaluate-job"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - name: Set up Python     
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12.5'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Login to W&B
        run: wandb login
      - name: Launch Job
        run: wandb launch -j "russratshin/registry-tutorial/job-source-registry-tutorial-regdemo.py:latest" -q "Queue One"
