name: "WandB Launch Job"
on:
  repository_dispatch:
    types: "launch-job"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
