name: "WandB Launch Job"
on:
  repository_dispatch:
    types: "launch-job"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - name: Get current date
        id: date
        #run: echo "TSTAMP=$(date +'%Y%m%d%H%M%S%N')" >> $GITHUB_ENV
        run: echo "TSTAMP=20240911011823116043" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - name: Set up Python     
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12.5'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Login to W&B
        run: wandb login
      - name: Launch Job
        #run: wandb launch -j "russratshin/registry-tutorial/job-source-registry-tutorial-regdemo.py:latest" -q "Queue One"
        run: wandb launch -j "russratshin/quicklaunch/job-source-quicklaunch-quicklaunch.py:v8" --config '{"overrides":{"args":["${{env.TSTAMP}}"]}}' -q "Queue One"
